[tool.poetry]
name = "welleng"
version = "0.7.3"
description = "A collection of Well Engineering tools"
authors = ["Jonathan Corcutt <jonnycorcutt@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/jonnymaserati/welleng"
repository = "https://github.com/python-poetry/poetry"
documentation = "https://jonnymaserati.github.io/welleng/build/html/index.html"
keywords = [
    "well",
    "trajectory",
    "wellpath",
    "wellbore",
    "drilling",
    "drill",
    "error",
    "separation",
    "minimum curvature",
    "iscwsa",
    "owsg",
    "well engineering",
    "wells",
    "drilling engineering",
    "directional drilling",
    "mwd",
    "survey",
    "covariance",
    "digitalization",
    "automation",
    "volve",
    "witsml",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering",
]
include = [
    {path = "errors/*.yaml"},
    {path = "errors/tool_codes/*.yaml"},
    {path = "exchange/*.yaml"}
]
exclude = ["tests"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.2"
scipy = "^1.10.1"
Pint = "^0.20.1"
PyYAML = "^6.0"
vtk = "^9.2.6"
magnetic-field-calculator = {version="^1.0.2", optional=true}
networkx = {version="^3.0", optional=true}
openpyxl = {version="^3.1.2", optional=true}
pandas = {version="^1.5.3", optional=true}
tabulate = {version="^0.9.0", optional=true}
trimesh = {version="^3.21.3", optional=true}
utm = {version="^0.7.0", optional=true}
vedo = {version="^2023.4.4", optional=true}
python-fcl = {version="^0.7.0", optional=true}

[tool.poetry.dev-dependencies]
# numba = {version="^0.56.4", optional=true}

[tool.poetry.extras]
easy = ["magnetic-field-calculator", "networkx", "openpyxl", "pandas",
    "tabulate", "trimesh", "utm", "vedo"]
advanced = ["magnetic-field-calculator", "networkx", "openpyxl", "pandas",
    "tabulate", "trimesh", "utm", "vedo", "python-fcl"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
